apps/invoice/urls.py
from django.conf import settings
from django.urls import re_path

import apps.invoice.views as invoice
from apps.invoice.apps import InvoiceConfig

app_name = InvoiceConfig.name

urlpatterns = [
    re_path(r"^invoice/(?P<pk>\d+)/$", invoice.InvoiceViews.as_view(), name="invoice"),
]

if settings.DEBUG:
    from django.contrib.staticfiles.urls import staticfiles_urlpatterns

    urlpatterns += staticfiles_urlpatterns()

apps/personalacc/urls.py
from django.urls import re_path

import apps.personalacc.views as personalacc
from apps.personalacc.apps import PersonalaccConfig

app_name = PersonalaccConfig.name

urlpatterns = [
    re_path(r"^user/$", personalacc.UserPageCreate.as_view(), name="user"),
    re_path(r"^manager/$", personalacc.ManagerPageCreate.as_view(), name="manager"),
    # Autocomplete
    re_path(r"^manager/autocomplete/$", personalacc.UserAutocomplete.as_view(), name="autocomplete"),
    
    re_path(r"^manager/formation_payments/$", personalacc.FormationPayments.as_view(), name="formation_payments"),
    re_path(r"^manager/receivable/$", personalacc.AccountsReceivableListView.as_view(), name="receivable"),
    
    re_path(r"^manager/house_history/$", personalacc.HouseHistoryListView.as_view(), name="house_history"),
    re_path(r"^manager/recalc_history/$", personalacc.RecalcHistoryListView.as_view(), name="recalc_history"),
    re_path(
        r"^manager/privileges_history/$", personalacc.PrivilegesHistoryListView.as_view(), name="privileges_history"
    ),
    re_path(r"^manager/subsidies_history/$", personalacc.SubsidiesHistoryListView.as_view(), name="subsidies_history"),
    re_path(r"^manager/payments_history/$", personalacc.PaymentsHistoryListView.as_view(), name="payments_history"),
]

newcity/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

import apps.mainapp.views as mainapp

urlpatterns = [
    path("", mainapp.IndexList.as_view(), name="main"),
    path("contact/", mainapp.ContactList.as_view(), name="contact"),
    path("news/", mainapp.NewstList.as_view(), name="news"),
    path("auth/", include("apps.authnapp.urls", namespace="auth")),
    path("directory/", include("apps.directory.urls", namespace="directory")),
    path("person/", include("apps.personalacc.urls", namespace="person")),
    path("invoice/", include("apps.invoice.urls", namespace="invoice")),
    path("admin/", admin.site.urls, name="admin"),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/personalacc/forms.py
from crispy_forms.helper import FormHelper
from dal import autocomplete
from django import forms

from apps.authnapp.models import User
from apps.directory.models import Privileges, Services, Subsidies
from apps.mainapp.models import (CurrentCounter, HouseCurrent, HouseHistory,
                            MainBook, Recalculations)


class MultipleForm(forms.Form):
    """Добавляем клас Мульти формности, идентификация форм будет по скрытому полю action"""

    action = forms.CharField(max_length=60, widget=forms.HiddenInput())


class CurrentCounterForm(forms.ModelForm):
    class Meta:
        model = CurrentCounter
        exclude = ("period", "electric_day", "electric_night", "electric_single", "created", "updated")

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # self.fields['user'].queryset = User.objects.filter(id=kwargs['initial']['user'])
        self.fields["user"].queryset = User.objects.filter(id=kwargs["initial"]["user"])
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"
            if field_name == 'user':
                field.label = 'Лицевой счет'
                field.widget.attrs['readonly'] = True
                
        self.helper = FormHelper()
        self.helper.form_show_labels = False


class HomeCurrentCounterForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"
        self.helper = FormHelper()
        self.helper.form_show_labels = False

    class Meta:
        model = HouseCurrent
        exclude = ("electric_day", "electric_night", "period", "created", "updated")


class HomeHistoryCounterForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"
        self.helper = FormHelper()
        # self.helper.form_show_labels = False

    class Meta:
        model = HouseHistory
        exclude = ("period", "created", "updated")


class RecalculationsForm(forms.ModelForm):
    
    class Meta:
        model = Recalculations
        exclude = ('period', 'is_auto', 'created', 'updated', 'is_active')
     
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Отправляем фильтрованные данные в форму
        self.fields["service"].queryset = Services.objects.filter(const=False)
        
        for field_name, field in self.fields.items():            
            if field_name == 'user':
                field.label = 'Лицевой счет'
                field.widget = forms.TextInput()
                field.widget.attrs['id'] = 'personalaccInpRecalc'

            field.widget.attrs['class'] = 'form-control  field_form'
            field.help_text = ''


class SubsidiesForm(forms.ModelForm):
    class Meta:
        model = Privileges
        exclude = ('is_active', 'created', 'updated')
     
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Отправляем фильтрованные данные в форму
        self.fields["service"].queryset = Services.objects.filter(const=False)
        
        for field_name, field in self.fields.items():            
            if field_name == 'user':
                field.label = 'Лицевой счет'
                field.widget = forms.TextInput()
                field.widget.attrs['id'] = 'personalaccInpSubsidies'

            field.widget.attrs['class'] = 'form-control  field_form'


class PrivilegesForm(forms.ModelForm):
    
    class Meta:
        model = Privileges
        exclude = ('is_active', 'created', 'updated')
     
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        # Отправляем фильтрованные данные в форму
        self.fields["service"].queryset = Services.objects.filter(const=False)
        
        for field_name, field in self.fields.items():            
            if field_name == 'user':
                field.label = 'Лицевой счет'
                field.widget = forms.TextInput()
                field.widget.attrs['id'] = 'personalaccInpPrivileges'

            field.widget.attrs['class'] = 'form-control  field_form'


class PaymentsForm(forms.ModelForm):
    
    class Meta:
        model = MainBook
        exclude = ("created", "updated", "is_active")
     
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["direction"].queryset = MainBook.objects.all().filter(direction="D")
        
        for field_name, field in self.fields.items():
            if field_name == 'period':
                field.label = 'Период'
                field.widget.attrs['readonly'] = True
            
            if field_name == 'user':
                field.label = 'Лицевой счет'
                field.widget = forms.TextInput()
                field.widget.attrs['id'] = 'personalaccInpPayments'

            field.widget.attrs['class'] = 'form-control  field_form'
            field.help_text = ''

apps/personalacc/views.py
import json
import datetime

from dal import autocomplete
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core import serializers
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView

from apps.authnapp.models import User
from apps.directory.models import Appartament, Privileges, Subsidies, UserProfile
from apps.invoice.views import starter
from apps.mainapp.models import (CurrentCounter, HistoryCounter, HouseCurrent,
                            HouseHistory, MainBook, PaymentOrder,
                            PersonalAccountStatus, Recalculations)
from apps.personalacc.forms import (CurrentCounterForm, HomeCurrentCounterForm,
                               HomeHistoryCounterForm, PaymentsForm,
                               PrivilegesForm, RecalculationsForm,
                               SubsidiesForm)
from apps.personalacc.models import SiteConfiguration


class UserPageCreate(LoginRequiredMixin, CreateView):
    model = User
    form_class = CurrentCounterForm
    context_object_name = "user"
    template_name = "personalacc/user_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["profiles"] = UserProfile.objects.get(user=self.request.user)
        context["credit"] = MainBook.get_user_credit(self.request.user)
        context["order"] = PaymentOrder.objects.filter(user=self.request.user)
        context["appartament"] = Appartament.objects.filter(user=self.request.user)
        context["history"] = HistoryCounter.get_last_val(self.request.user)
        context["title"] = "Пользователь | ООО Новый город"
        return context

    def get_form_kwargs(self, *args, **kwargs):
        kwargs = super().get_form_kwargs(*args, **kwargs)
        # Заполняем форму начальными данными
        kwargs["initial"] = {"user": self.request.user.id}
        return kwargs

    def get_queryset(self):
        qs = super().get_queryset()
        return qs.get(pk=self.request.user.id)

    def post(self, request, *args, **kwargs):
        if self.request.is_ajax and self.request.method == "POST":
            if self.request.POST.get("form_type") == "counterForm":
                data = self.get_form_kwargs()
                form = self.form_class(self.request.POST, initial=data["initial"])

            if form.is_valid():
                post = self.request.POST
                user = self.request.user
                period = datetime.datetime.now().date().replace(day=1)
                # TODO PERIOD
                # period = PERIOD
                update_values = {
                    "col_water": post.get("col_water"),
                    "hot_water": post.get("hot_water"),
                }
                obj, created = CurrentCounter.objects.update_or_create(user=user, period=period, defaults=update_values)
                # При создании новой записи удаляем старую
                if created:
                    previous_month = (period - datetime.timedelta(days=1)).replace(day=1)
                    previous_value = CurrentCounter.objects.filter(user=user, period=previous_month)
                    previous_value.delete()
                data = serializers.serialize(
                    "json",
                    [
                        obj,
                    ],
                )
                return JsonResponse({"instance": data}, status=200)
            else:
                return JsonResponse({"error": form.errors}, status=400)
        return JsonResponse({"error": ""}, status=400)


class ManagerPageCreate(LoginRequiredMixin, CreateView):
    form_class = HomeCurrentCounterForm
    form_classes = {
        "house_count_form": HomeCurrentCounterForm,
        "house_history_form": HomeHistoryCounterForm,
        "recalculations_form": RecalculationsForm,
        "privilege_form": PrivilegesForm,
        "subsidies_form": SubsidiesForm,
        "payments_form": PaymentsForm,
    }
    template_name = "personalacc/manager_list.html"
    success_url = reverse_lazy("person:manager")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        for name, form in self.form_classes.items():
            if name not in context:
                context[name] = form()
        context["config"] = SiteConfiguration.get_solo()
        context["house_history"] = HouseHistory.get_qty_last_items(5)
        context["house_current"] = HouseCurrent.get_qty_last_items(5)
        context["house_rec"] = Recalculations.get_qty_last_items(5)
        context["house_privileges"] = Privileges.get_qty_last_items(5)
        context["house_subsidies"] = Subsidies.get_qty_last_items(5)
        context["house_pay_debit"] = MainBook.get_qty_last_items(5)
        context["title"] = "Менеджер | ООО Новый город"
        return context

    def post(self, *args, **kwargs):
        post = self.request.POST.copy()
        user = None
        if post.__contains__('user'):
            personalacc = post.get('user')[:7]
            user = User.get_by_user_acc(personalacc)
            # Удаляем кривого юзера str и не нужную инфу
            post.pop('user')
            # Устанавливаем id юзера для корректного сохранения данных
            post.__setitem__('user', user.id)
        # TODO PERIOD
        # period = PERIOD
        period = datetime.datetime.now().date().replace(day=1)
        handle = {
            "house_count_form": self.house_count_process,
            "recalculations_form": self.recalculations_process,
            "privilege_form": self.privilege_process,
            "subsidies_form": self.subsidies_process,
            "payments_form": self.payments_process,
        }
        if self.request.is_ajax and self.request.method == "POST":
            type_form = post.get("form_type")
            for cls, el in self.form_classes.items():
                if type_form == cls:
                    form = el(post)
                    if form.is_valid():
                        func = handle[cls]
                        ser_instance = func(self, form=form, post=post, user=user.id if user else None, period=period)
                        return JsonResponse({"instance": ser_instance}, status=200)
                    else:
                        return JsonResponse({"error": form.errors}, status=400)
        return JsonResponse({"error": ""}, status=400)

    def house_count_process(self, *args, **kwargs):
        house = kwargs["post"].get("house")
        update_values = {
            "col_water": kwargs["post"].get("col_water"),
            "hot_water": kwargs["post"].get("hot_water"),
            # "electric_day": post.get("electric_day"),
            # "electric_night": post.get("electric_night"),
        }
        obj, created = HouseCurrent.objects.update_or_create(
            house_id=house, period=kwargs["period"], defaults=update_values
        )
        # При создании новой записи удаляем старую
        if created:
            previous_month = (kwargs["period"] - datetime.timedelta(days=1)).replace(day=1)
            previous_value = HouseCurrent.objects.filter(house_id=house, period=previous_month)
            previous_value.delete()
        instance = HouseCurrent.get_qty_last_items(5)
        content = {"house_current": instance}
        result = render_to_string("personalacc/includes/house_current_short_history.html", content)
        return result

    def recalculations_process(self, *args, **kwargs):
        update_values = {"recalc": kwargs["post"].get("recalc"), "desc": kwargs["post"].get("desc")}
        obj, created = Recalculations.objects.update_or_create(
            user_id=kwargs["user"],
            period=kwargs["period"],
            service_id=kwargs["post"].get("service"),
            is_auto=False,
            defaults=update_values,
        )
        instance = Recalculations.get_qty_last_items(5)
        content = {"house_rec": instance}
        result = render_to_string("personalacc/includes/recalc_short_story.html", content)
        return result

    def privilege_process(self, *args, **kwargs):
        update_values = {"sale": kwargs["post"].get("sale"), "desc": kwargs["post"].get("desc")}
        obj, created = Privileges.objects.update_or_create(
            user_id=kwargs["user"], service_id=kwargs["post"].get("service"), defaults=update_values
        )
        instance = Privileges.get_qty_last_items(5)
        content = {"house_privileges": instance}
        result = render_to_string("personalacc/includes/privileges_short_story.html", content)
        return result

    def subsidies_process(self, *args, **kwargs):
        update_values = {"sale": kwargs["post"].get("sale"), "desc": kwargs["post"].get("desc")}
        obj, created = Subsidies.objects.update_or_create(
            user_id=kwargs["user"], service_id=kwargs["post"].get("service"), defaults=update_values
        )
        instance = Subsidies.get_qty_last_items(5)
        content = {"house_subsidies": instance}
        result = render_to_string("personalacc/includes/subsidies_short_story.html", content)
        return result

    def payments_process(self, *args, **kwargs):
        update_values = {"direction": kwargs["post"].get("direction"), "amount": kwargs["post"].get("amount")}
        obj, created = MainBook.objects.update_or_create(
            user_id=kwargs["user"], period=kwargs["period"], defaults=update_values
        )
        instance = MainBook.get_qty_last_items(5)
        content = {"house_pay_debit": instance}
        result = render_to_string("personalacc/includes/payments_short_story.html", content)
        return result


class HouseHistoryListView(LoginRequiredMixin, ListView):
    model = HouseHistory
    paginate_by = 50
    context_object_name = "history"
    template_name = "personalacc/house_history_list.html"

templates/personalacc/user_list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% load crispy_forms_tags %}


{% block menu %}
    {% include 'mainapp/includes/inc_menu.html' %}
{% endblock menu %}

{% block content %}
    <div class="intro-user  mt-5">
        <div class="container">
            <h2 class="intro-user__title  text-center">Здравствуйте, {{ user.name }}</h2>
        </div>
    </div>
    <div class="user-area">
        <div class="container">
            <h4 class="user-area__title  mt-3  mb-3">Личный кабинет</h4>
        </div>
    </div>
    <div class="tenants">
        <div class="container">
            <div class="d-flex  flex-row  tenants__item  flex-column">

                <!-- Nav-TABS -->
                <ul class="nav nav-tabs  mb-5" id="myTab" role="tablist">
                    <li class="nav-item" role="presentation">
                        <a class="nav-link active" id="home-tab" data-toggle="tab" href="#home" role="tab"
                            aria-controls="home" aria-selected="true">Общая информация</a>
                    </li>
                    <li class="nav-item" role="presentation">
                        <a class="nav-link" id="profile-tab" data-toggle="tab" href="#testimony" role="tab"
                            aria-controls="profile" aria-selected="false">Подать показания</a>
                    </li>
                    <li class="nav-item" role="presentation">
                        <a class="nav-link" id="contact-tab" data-toggle="tab" href="#history" role="tab"
                            aria-controls="contact" aria-selected="false">История начислений</a>
                    </li>
                </ul>

                <!-- Tabs-CONTENT -->
                <div class="tab-content  pb-5  mb-5" id="myTabContent">

                    <!-- Tab-HOME -->
                    <div class="tab-pane  fade  show  active  user-area__table" id="home" role="tabpanel" aria-labelledby="home-tab">
                        
                        <p class="user-area__subtitle  text-700  mb-4">Ваши персональные данные</p>
                        <table class="table table-striped">
                            {% if user.is_active %}
                            <tbody>
                                <tr>
                                    <th scope="row">ФИО</th>
                                    <td>{{ user.name }}</td>
                                </tr>
                                <tr>
                                    <th scope="row">Лицевой счет</th>
                                    <td>{{ user.personal_account }}</td>
                                </tr>
                                <tr>
                                    <th scope="row">E-mail</th>
                                    <td>{{ user.email }}</td>
                                </tr>
                                <tr>
                                    <th scope="row">Телефон</th>
                                    <td>{{ user.phone }}</td>
                                </tr>
                                <tr>
                                    <th scope="row">Город</th>
                                    <td>{{ appartament.0.house.city.city }}</td>
                                </tr>
                                <tr>
                                    <th scope="row">Адрес</th>
                                    <td>
                                        {{ appartament.0 }}
                                    </td>
                                </tr>
                            </tbody>
                            {% endif %}
                        </table>
                    </div>

                    <!-- Tab-COUNTER -->
                    <div class="tab-pane  fade  user-area__table" id="testimony" role="tabpanel" aria-labelledby="profile-tab">
                        <h4 class="mb-3">Введите показания счетчиков в поля</h4>
                            <div class="alert alert-warning" role="alert">
                                <ul class="">
                                    <li><span class="text-700">Счетчик ГВС</span> (горячая вода), укажите целое число до запятой</li>
                                    <li><span class="text-700">Счетчик ХВС</span> (холодная вода), укажите целое число до запятой</li>
                                    
                                    {% comment 'Заказчик отменил пока'%}
                                        {% if user.profiles.type_electric_meter == '2' %}
                                            <li><span class="text-700">Электроэнергия (день)</span>, укажите целое число до запятой</li>
                                            <li><span class="text-700">Электроэнергия (ночь)</span>, укажите целое число до запятой</li>
                                        {% else %}
                                            <li><span class="text-700">Электроэнергия</span>, укажите целое число до запятой</li>
                                        {% endif %}
                                    {% endcomment %}

                                    <li>Нажать кнопку <span class="text-700">СОХРАНИТЬ</span></li>
                                </ul>
                            </div>

                        {% now "d" as today %}
                        {% if "01" < today and today < "31" %}
                            <h4 class="mt-5">Таблица для заполнения</h4>
                            <div class="">
                                <form id="counterForm" method="POST" name="counterForm">
                                    {% csrf_token %}
                                    <input type="hidden" name="form_type" value="counterForm">
            
                                    <div class="user-area__table">
                                        <table class="user-area__table  table">
                                            <thead>
                                                <tr>
                                                    <th scope="col"></th>
                                                    <th class="text-center" scope="col">Показания</th>
                                                </tr>
                                            </thead>
                                            <tbody>
                                                <tr>
                                                    <th scope="row" type>Пользователь:</th>
                                                    <td class="text-center" id="userName">{{ form.user|as_crispy_field }}</td>
                                                </tr>
                                                <tr>
                                                    <th scope="row">Холодная вода:</th>
                                                    <td class="text-center" id="electricDay">{{ form.col_water|as_crispy_field }}</td>
                                                </tr>
                                                <tr>
                                                    <th scope="row">Горячая вода:</th>
                                                    <td class="text-center" id="electricNight">{{ form.hot_water|as_crispy_field }}</td>
                                                </tr>
                                                {% comment 'Электроэнергию не считаем'%}
                                                    {% if user.profiles.type_electric_meter == '2' %}
                                                    <tr>
                                                        <th scope="row">Электроэнергия день:</th>
                                                        <td class="text-center" id="electricDay">{{ form.electric_day|as_crispy_field }}</td>
                                                    </tr>
                                                    <tr>
                                                        <th scope="row">Электроэнергия ночь:</th>
                                                        <td class="text-center" id="electricNight">{{ form.electric_night|as_crispy_field }}</td>
                                                    </tr>
                                                    {% elif user.profiles.type_electric_meter == '1'  %}
                                                    <tr>
                                                        <th scope="row">Электроэнергия:</th>
                                                        <td class="text-center" id="electricSingle">{{ form.electric_single|as_crispy_field }}</td>
                                                    </tr>
                                                    {% endif %}
                                                    {% if user.profiles.type_electric_meter == '2' %}
                                                    <tr>
                                                        <th scope="row">Электроэнергия день:</th>
                                                        <td class="text-center" id="electricDay">{{ form.electric_day|as_crispy_field }}</td>
                                                    </tr>
                                                    <tr>
                                                        <th scope="row">Электроэнергия ночь:</th>
                                                        <td class="text-center" id="electricNight">{{ form.electric_night|as_crispy_field }}</td>
                                                    </tr>
                                                    {% elif user.profiles.type_electric_meter == '1'  %}
                                                    <tr>
                                                        <th scope="row">Электроэнергия:</th>
                                                        <td class="text-center" id="electricSingle">{{ form.electric_single|as_crispy_field }}</td>
                                                    </tr>
                                                    {% endif %}
                                                {% endcomment %}
                                            </tbody>
                                        </table>
                                    </div>
                                    <button action="{% url 'person:user' %}" type="button" class="form-control  bg-success  text-white  new_category_form--save" id="counterBtn">Сохранить</button>
                                </form>
                            </div>
                        {% else %}
                            <div class="alert alert-danger" role="alert">
                                ВНИМАНИЕ! Показания принимаются с 20 по 26 число каждого месяца!
                            </div>
                        {% endif %}
                    </div>

                    <!-- Tab-HISTORY -->
                    <div class="tab-pane fade" id="history" role="tabpanel" aria-labelledby="contact-tab">
                        <h4 class="mb-3">История начислений</h4>
                        <div class="user-area__history-tab">
                            <table class="table">
                                <thead class="thead-light">
                                    <tr>
                                        <th scope="col">Месяц</th>
                                        <th class="text-center" scope="col">Сумма</th>
                                        <th class="text-center" scope="col">Квитанция</th>
                                        <th class="text-center" scope="col">Оплатить</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    {% for el in order %}
                                    <tr>
                                        <td>{{ el.period|date:"m - Y" }}</td>
                                        <td class="text-center">{% if el.amount > 0 %}{{el.amount}}{% else %}0{% endif %} руб.</td>
                                        <td class="text-center"><a class="btn btn-light border border-secondary  btn-sm" href="{% url 'invoice:invoice' el.id %}" role="button">Квитанция</a></td>
                                        {% comment %}оплачено или нет? Делать проверку и отображать если не оплачено!{% endcomment %}
                                        <td class="text-center"><a href="#" class="text-decoration-none">Оплатить</a></td>
                                    </tr>
                                    {% endfor %}
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

{% block js %}
    <script src="{% static 'js/paccount/form_list.js' %}"></script>
    <script src="{% static 'js/paccount/autocomplete.js' %}"></script>
{% endblock js %}

{% block footer %}
    <script>
        // Слушает инпут на изменение (Autocomplete)
        document.addEventListener('input', function(e) {
            let subStr = 'personalaccInp';
            if (e.target.id.includes(subStr)) {
                autocomplete(e.target);
            }
        });
    </script>
{% endblock footer %}