apps/directory/urls.py
from django.urls import re_path

import apps.directory.views as directory
from apps.personalacc.apps import PersonalaccConfig

app_name = PersonalaccConfig.name

urlpatterns = [
    re_path(r"^$", directory.DirectoryList.as_view(), name="list"),
    # ServicesCategory
    re_path(r"^categories/create/$", directory.ServicesCategoryCreateView.as_view(), name="category_create"),
    re_path(
        r"^categories/update/(?P<pk>\d+)/$", directory.ServicesCategoryUpdateView.as_view(), name="category_update"
    ),
    re_path(
        r"^categories/delete/(?P<pk>\d+)/$", directory.ServicesCategoryDeleteView.as_view(), name="category_delete"
    ),
    # Services
    re_path(r"^services/create/category/(?P<pk>\d+)/$", directory.ServicesCreateView.as_view(), name="services_create"),
    re_path(r"^services/read/category/(?P<pk>\d+)/$", directory.ServicesListView.as_view(), name="services"),
    re_path(r"^services/update/(?P<pk>\d+)/$", directory.ServicesUpdateView.as_view(), name="services_update"),
    re_path(r"^services/delete/(?P<pk>\d+)/$", directory.ServicesDeleteView.as_view(), name="services_delete"),
    # City
    re_path(r"^city/create/$", directory.CityCreateView.as_view(), name="city_create"),
    re_path(r"^city/update/(?P<pk>\d+)/$", directory.CityUpdateView.as_view(), name="city_update"),
    re_path(r"^city/delete/(?P<pk>\d+)/$", directory.CityDeleteView.as_view(), name="city_delete"),
    # Street
    re_path(r"^street/create/city/(?P<pk>\d+)/$", directory.StreetCreateView.as_view(), name="street_create"),
    re_path(r"^street/read/city/(?P<pk>\d+)/$", directory.StreetListView.as_view(), name="streets"),
    re_path(r"^street/update/(?P<pk>\d+)/$", directory.StreetUpdateView.as_view(), name="street_update"),
    re_path(r"^street/delete/(?P<pk>\d+)/$", directory.StreetDeleteView.as_view(), name="street_delete"),
    # House
    re_path(r"^house/create/street/(?P<pk>\d+)/$", directory.HouseCreateView.as_view(), name="house_create"),
    re_path(r"^house/read/street/(?P<pk>\d+)/$", directory.HouseListView.as_view(), name="house"),
    re_path(r"^house/update/(?P<pk>\d+)/$", directory.HouseUpdateView.as_view(), name="house_update"),
    re_path(r"^house/delete/(?P<pk>\d+)/$", directory.HouseDeleteView.as_view(), name="house_delete"),
    # Appartaments
    re_path(
        r"^appartaments/create/house/(?P<pk>\d+)/$",
        directory.AppartamentsCreateView.as_view(),
        name="appartaments_create",
    ),
    re_path(r"^appartaments/read/house/(?P<pk>\d+)/$", directory.AppartamentsListView.as_view(), name="appartaments"),
    re_path(
        r"^appartaments/update/(?P<pk>\d+)/$", directory.AppartamentsUpdateView.as_view(), name="appartaments_update"
    ),
    re_path(
        r"^appartaments/delete/(?P<pk>\d+)/$", directory.AppartamentsDeleteView.as_view(), name="appartaments_delete"
    ),
    # Residents
    re_path(r"^resident/read/$", directory.ResidentsListView.as_view(), name="residents"),
    re_path(r"^resident/create/$", directory.ResidentsCreateView.as_view(), name="residents_create"),
    re_path(r"^resident/update/(?P<pk>\d+)/$", directory.ResidentsUpdateView.as_view(), name="residents_update"),
    re_path(r"^resident/delete/(?P<pk>\d+)/$", directory.ResidentsDeleteView.as_view(), name="residents_delete"),
]

newcity/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

import apps.mainapp.views as mainapp

urlpatterns = [
    path("", mainapp.IndexList.as_view(), name="main"),
    path("contact/", mainapp.ContactList.as_view(), name="contact"),
    path("news/", mainapp.NewstList.as_view(), name="news"),
    path("auth/", include("apps.authnapp.urls", namespace="auth")),
    path("directory/", include("apps.directory.urls", namespace="directory")),
    path("person/", include("apps.personalacc.urls", namespace="person")),
    path("invoice/", include("apps.invoice.urls", namespace="invoice")),
    path("admin/", admin.site.urls, name="admin"),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/directory/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import transaction
from django.shortcuts import HttpResponseRedirect, get_object_or_404
from django.urls import reverse_lazy
from django.views.generic import CreateView, DeleteView, ListView, UpdateView

from apps.authnapp.managers import UserManager
from apps.authnapp.models import User
from apps.directory.forms import (AppartamentFormSet, AppartamentsEditForm,
                             CityEditForm, HouseEditForm, ResidentsEditForm,
                             ServicesCategoryEditForm, ServicesEditForm,
                             StreetEditForm)

from .models import (Appartament, City, House, Services, ServicesCategory,
                     Street)


class DirectoryList(LoginRequiredMixin, ListView):
    model = User
    template_name = "directory/directory_list.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["residents"] = User.objects.filter(is_staff=False).filter(is_superuser=False)
        context["categories"] = ServicesCategory.objects.all()
        context["city"] = City.objects.all()
        return context


"""
================
PRODUCT CATEGOTY
================
"""


class ServicesCategoryCreateView(LoginRequiredMixin, CreateView):
    model = ServicesCategory
    template_name = "directory/category_update.html"
    success_url = reverse_lazy("directory:list")
    form_class = ServicesCategoryEditForm


class ServicesCategoryUpdateView(LoginRequiredMixin, UpdateView):
    model = ServicesCategory
    template_name = "directory/category_update.html"
    success_url = reverse_lazy("directory:list")
    form_class = ServicesCategoryEditForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Категории/редактирование"
        return context


class ServicesCategoryDeleteView(LoginRequiredMixin, DeleteView):
    model = ServicesCategory
    template_name = "directory/category_delete.html"
    success_url = reverse_lazy("directory:list")

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


"""
=========
SERVICES
=========
"""


class ServicesListView(LoginRequiredMixin, ListView):
    model = Services
    template_name = "directory/services.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["category"] = get_object_or_404(ServicesCategory, pk=self.kwargs["pk"])
        context["services"] = Services.objects.filter(category__pk=self.kwargs["pk"]).order_by("name")
        return context


class ServicesCreateView(LoginRequiredMixin, CreateView):
    model = Services
    template_name = "directory/services_update.html"
    success_url = reverse_lazy("directory:list")
    form_class = ServicesEditForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Тариф/создание"
        return context


class ServicesUpdateView(LoginRequiredMixin, UpdateView):
    model = Services
    template_name = "directory/services_update.html"
    success_url = reverse_lazy("directory:list")
    form_class = ServicesEditForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Тариф/редактирование"
        return context


class ServicesDeleteView(LoginRequiredMixin, DeleteView):
    model = Services
    template_name = "directory/services_delete.html"
    success_url = reverse_lazy("directory:list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Тариф/удаление"
        return context

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


"""
==========
   CITY
==========
"""


class CityCreateView(LoginRequiredMixin, CreateView):
    model = City
    template_name = "directory/city_update.html"
    success_url = reverse_lazy("directory:list")
    form_class = CityEditForm


class CityUpdateView(LoginRequiredMixin, UpdateView):
    model = City
    template_name = "directory/city_update.html"
    success_url = reverse_lazy("directory:list")
    form_class = CityEditForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Города/редактирование"
        return context


class CityDeleteView(LoginRequiredMixin, DeleteView):
    model = City
    template_name = "directory/city_delete.html"
    success_url = reverse_lazy("directory:list")

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


"""
==========
  STREET
==========
"""


class StreetListView(LoginRequiredMixin, ListView):
    model = Street
    paginate_by = 50
    template_name = "directory/streets.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["city"] = get_object_or_404(City, pk=self.kwargs["pk"])
        context["streets"] = Street.objects.filter(city__pk=self.kwargs["pk"]).order_by("id")
        return context
    
    def get_queryset(self):
        qs = Street.objects.filter(city__pk=self.kwargs["pk"]).order_by("id")
        return qs


class StreetCreateView(LoginRequiredMixin, CreateView):
    model = Street
    template_name = "directory/street_update.html"
    success_url = reverse_lazy("directory:list")
    form_class = StreetEditForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["city"] = self.kwargs["pk"]
        context["title"] = "Улица/создание"
        return context


class StreetUpdateView(LoginRequiredMixin, UpdateView):
    model = Street
    template_name = "directory/street_update.html"
    success_url = reverse_lazy("directory:list")
    form_class = StreetEditForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["city"] = self.kwargs["pk"]
        context["title"] = "Улица/редактирование"
        return context


class StreetDeleteView(LoginRequiredMixin, DeleteView):
    model = Street
    template_name = "directory/street_delete.html"
    success_url = reverse_lazy("directory:list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Улица/удаление"
        return context

    def delete(self, request, *args, **kwargs):
        self.object = self.get_object()
        self.object.is_active = False
        self.object.save()
        return HttpResponseRedirect(self.get_success_url())


"""
=========
  HOUSE
=========
"""


class HouseListView(LoginRequiredMixin, ListView):
    model = House
    template_name = "directory/house.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["street"] = get_object_or_404(Street, pk=self.kwargs["pk"])
        context["house"] = House.objects.filter(street__pk=self.kwargs["pk"]).order_by("street")
        return context


class HouseCreateView(LoginRequiredMixin, CreateView):
    model = House
    template_name = "directory/house_update.html"
    success_url = reverse_lazy("directory:list")
    form_class = HouseEditForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Дом/создание"
        return context


class HouseUpdateView(LoginRequiredMixin, UpdateView):
    model = House
    template_name = "directory/house_update.html"
    success_url = reverse_lazy("directory:list")
    form_class = HouseEditForm

    # def get_queryset(self):
    #     return House.objects.all()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Дом/редактирование"

        if self.request.POST:
            context["appartament_form"] = AppartamentFormSet(self.request.POST, instance=self.object)
        else:
            queryset = self.object.appartament_set.filter(is_active=True).select_related()
            formset = AppartamentFormSet(instance=self.object, queryset=queryset)
            context["appartament_form"] = formset
        return context

    # def post(self, request, *args, **kwargs):
    #     self.object = self.get_object()
    #     form_class = self.get_form_class()
    #     form = self.get_form(form_class)
    #     formset = AppartamentFormset(self.request.POST, instance=self.object)

    #     if form.is_valid() and formset.is_valid():
    #         return self.form_valid(form, formset)

    #     return self.form_invalid(form, formset)

    def form_valid(self, form):
        """
        Called if all forms are valid. Creates a Author instance along
        with associated books and then redirects to a success page.
        """
        context = self.get_context_data()
        appartament_form = context["appartament_form"]

        with transaction.atomic():
            self.object = form.save()
            if appartament_form.is_valid():
                appartament_form.instance = self.object
                appartament_form.save()

        return super().form_valid(form)


class HouseDeleteView(LoginRequiredMixin, DeleteView):
    model = House
    template_name = "directory/house_delete.html"
    success_url = reverse_lazy("directory:list")

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Дом/удаление"

templates/directory/appartaments_delete.html
{% extends 'directory/base.html' %}
{% load staticfiles %}

{% block menu %}
    {% include 'directory/includes/inc_menu.html' %}
{% endblock menu %}

{% block content %}
    <div class="directory__form">
        <p class="category_delete--text">Уверены, что хотите удалить <strong>квартиру № {{ object.number }} ({{ object.house }})</strong>?</p> 
        <div class="category__form">
            <form action="{% url 'directory:appartaments_delete' object.pk %}" method="post">
                {% csrf_token %}

                <div class="form-group  d-flex  justify-content-around  mt-5">
                    <input class="btn  btn-danger" type="submit" value="удалить">
                    <a class="btn  btn-success" role="button" onclick="javascript:history.back(); return false;">отмена</a>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/directory/category_delete.html
{% extends 'directory/base.html' %}
{% load staticfiles %}

{% block menu %}
    {% include 'directory/includes/inc_menu.html' %}
{% endblock menu %}

{% block content %}
    <div class="directory__form">
        <p class="category_delete--text">Уверены, что хотите удалить категорию <strong>{{ object.name }}</strong>?</p> 
        <div class="category__form">
            <form action="{% url 'directory:category_delete' object.pk %}" method="post">
                {% csrf_token %}

                <div class="form-group  d-flex  justify-content-around  mt-5">
                    <input class="btn  btn-danger" type="submit" value="удалить">
                    <a class="btn  btn-success" role="button" onclick="javascript:history.back(); return false;">отмена</a>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/directory/city_delete.html
{% extends 'directory/base.html' %}
{% load staticfiles %}

{% block menu %}
    {% include 'directory/includes/inc_menu.html' %}
{% endblock menu %}

{% block content %}
    <div class="directory__form">
        <p class="category_delete--text">Уверены, что хотите удалить город <strong>{{ object.city }}</strong>?</p> 
        <div class="category__form">
            <form action="{% url 'directory:category_delete' object.pk %}" method="post">
                {% csrf_token %}

                <div class="form-group  d-flex  justify-content-around  mt-5">
                    <input class="btn  btn-danger" type="submit" value="удалить">
                    <a class="btn  btn-success" role="button" onclick="javascript:history.back(); return false;">отмена</a>
                </div>
            </form>
        </div>
    </div>
{% endblock %}

templates/directory/directory_list.html
{% extends 'directory/base.html' %}
{% load staticfiles %}

{% load auth_extras %}
{% load crispy_forms_tags %}

{% block menu %}
    {% include 'directory/includes/inc_menu.html' %}
{% endblock menu %}

{% block content %}
    <div class="manager__directory-tab">
        <div class="row">
            <div class="col-4">
                <div class="nav flex-column nav-pills" id="v-pills-tab" role="tablist"
                    aria-orientation="vertical">
                    <a class="nav-link active" id="v-pills-city-tab" data-toggle="pill"
                        href="#v-pills-city" role="tab" aria-controls="v-pills-city"
                        aria-selected="true">Города, улицы, дома</a>
                    <a class="nav-link" id="v-pills-resident-tab" data-toggle="pill"
                        href="#v-pills-resident" role="tab" aria-controls="v-pills-resident"
                        aria-selected="false">Жильцы</a>
                    <a class="nav-link" id="v-pills-rate-tab" data-toggle="pill"
                        href="#v-pills-rate" role="tab" aria-controls="v-pills-rate"
                        aria-selected="false">Тарифы</a>
                </div>
            </div>

            <div class="col-8">
                <div class="tab-content" id="v-pills-tabContent">

                    <!-- Link-CITY -->
                    <div class="manager-tab__city  tab-pane  fade show active" id="v-pills-city"
                        role="tabpanel" aria-labelledby="v-pills-home-tab">

                        <a class="btn  btn-outline-primary  new__category  btn-sm  mb-5" href="{% url 'directory:city_create' %}" role="button">новый город</a>

                        <h4>Города</h4>
                        <table class="table">
                            <thead class="thead-light">
                                <tr>
                                    <th scope="col">ID</th>
                                    <th scope="col">Город</th>
                                    <th class="text-center" scope="col">Список</th>
                                    <th class="text-center" scope="col">редактировать</th>
                                    <th class="text-center" scope="col">удалить</th>
                                </tr>
                            </thead>
                            {% for city in city %}
                            <tbody>
                                <tr>
                                    <th scope="row">{{ city.id }}</th>
                                    <td>{{ city.city }}</td>
                                    <td class="text-center"><a type="button" class="btn btn-outline-primary btn-sm" role="button" href="{% url 'directory:streets' city.pk %}">Улицы</a></td>
                                    <td class="text-center"><a type="button" class="btn btn-outline-warning btn-sm" role="button" href="{% url 'directory:city_update' city.pk %}">Редактировать</a></td>
                                    <td class="text-center"><a class="text-danger text-decoration-none" href="{% url 'directory:city_delete' city.pk %}">удалить</a></td>
                                </tr>
                            </tbody>
                            {% endfor %}
                        </table>
                    </div><!-- ./manager-tab__city -->

                    <!-- Link-RESIDENT -->
                    <div class="manager-tab__resident  tab-pane fade" id="v-pills-resident"
                        role="tabpanel" aria-labelledby="v-pills-resident-tab">

                        <div class='d-flex  justify-content-between  pb-5'>
                            <a href="{% url 'directory:residents_create' %}" class="btn btn-outline-primary btn-sm" role="button">Добавить жильца</a>
                            <a href="{% url 'directory:residents' %}" class="btn btn-outline-primary btn-sm" role="button">Все жильцы</a>
                        </div>


                        <h4>Жильцы</h4>
                        <table class="table">
                            <thead class="thead-light">
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Лицевой счет</th>
                                    <th scope="col">ФИО</th>
                                    <th scope="col">редактировать</th>
                                </tr>
                            </thead>
                            {% for resident in residents %}
                                <tbody>
                                    <tr>
                                        <th scope="row">{{ resident.id }}</th>
                                        <td>{{ resident.personal_account }}</td>
                                        <td>{{ resident.name }}</td>
                                        <td><a href="{% url 'directory:residents_update' resident.pk %}"  type="button" class="btn btn-outline-warning btn-sm" role="button">редактировать</a>
                                        </td>
                                    </tr>
                                </tbody>
                            {% endfor %}
                        </table>
                    </div><!-- ./manager-tab__object -->

                    <!-- Link-RATE -->
                    <div class="tab-pane fade" id="v-pills-rate" role="tabpanel"
                        aria-labelledby="v-pills-rate-tab">

                        <a class="btn  btn-outline-primary  new__category  btn-sm " href="{% url 'directory:category_create' %}" role="button">новая категория</a>

                        <h4 class="mb-3  mt-5">Категории тарифов</h4>

                        <table class="table">
                            <thead class="thead-light">
                                <tr>
                                    <th scope="col">#</th>
                                    <th scope="col">Наименование</th>
                                    <th class="text-center" scope="col">Список</th>
                                    <th class="text-center" scope="col">Редактировать</th>
                                    <th class="text-center" scope="col">Удалить</th>
                                </tr>
                            </thead>

                            {% for category in categories %}
                                <tbody>
                                    <tr class="{% if not category.is_active %}not_active{% endif %}">
                                        <th scope="row">{{ category.id }}</th>
                                        <td>{{ category.name }}</td>
                                        <td class="text-center"><a type="button" class="btn btn-outline-primary btn-sm" role="button" href="{% url 'directory:services' category.pk %}">Тарифы категории</a></td>
                                        <td class="text-center"><a type="button" class="btn btn-outline-warning btn-sm" role="button" href="{% url 'directory:category_update' category.pk %}">Редактировать</a></td>
                                        <td class="text-center"><a class="text-danger text-decoration-none" href="{% url 'directory:category_delete' category.pk %}">удалить</a></td>
                                    </tr>
                                </tbody>
                            {% endfor %}

                        </table>

                    </div>
                </div>
            </div>

        </div><!-- ./row -->
    </div><!-- ./manager__directory-tab -->
{% endblock %}

templates/directory/residents.html
{% extends 'directory/base.html' %}
{% load staticfiles %}

{% load crispy_forms_tags %}

{% block menu %}
    {% include 'directory/includes/inc_menu.html' %}
{% endblock menu %}

{% block content %}
    <div class="row  mt-5  mb-3  d-flex justify-content-between">
        <h4 class="col">Жильцы: </span></h4>
        <div class="form-group">
            <a href="{% url 'directory:residents_create' %}" class="btn btn-outline-primary btn-sm" role="button">Добавить жильца</a>
            <a class="btn  btn-outline-secondary btn-sm" onclick="javascript:history.back(); return false;" role="button">Назад</a>
        </div>
        
    </div>
    <div class="manager-area__counters-history  mb-5">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th class="text-left" scope="col">Лицевой счет</th>
                    <th class="text-left" scope="col">ФИО</th>
                    <th class="text-center" scope="col">Почта</th>
                    <th class="text-center" scope="col">Телефон</th>
                    <th class="text-center" scope="col">Редактировать</th>
                    <th class="text-center" scope="col">Удалить</th>
                </tr>
            </thead>
            {% for item in residents %}
            <tbody>
                <tr>
                    <td>{{ item.id }}</td>
                    <td class="text-left">{{ item.personal_account }}</td>
                    <td class="text-left">{{ item.name }}</td>
                    <td class="text-left">{{ item.email }}</td>
                    <td class="text-left">{{ item.phone }}</td>
                    <td><a href="{% url 'directory:residents_update' item.pk %}" type="button" class="btn btn-outline-warning btn-sm" role="button">Редактировать</a></td>
                    <td><a href="{% url 'directory:residents_delete' item.pk %}" class="text-danger text-decoration-none">удалить</a></td>
                </tr>
            </tbody>
            {% endfor %}

        </table> 
    </div>
{% endblock %}

templates/directory/services.html
{% extends 'directory/base.html' %}
{% load staticfiles %}

{% load crispy_forms_tags %}

{% block menu %}
    {% include 'directory/includes/inc_menu.html' %}
{% endblock menu %}

{% block content %}
    <div class="row  mt-5  mb-3  d-flex justify-content-between">
        <h4 class="col">Тарифы:  <span class="text-700">{{ category.name }}</span></h4>
        <div class="form-group">
            <a href="{% url 'directory:services_create' category.pk %}" class="btn btn-outline-primary btn-sm" role="button">добавить тариф</a>
            <a href="{% url 'directory:list' %}" class="btn  btn-outline-secondary btn-sm" role="button">назад</a>
        </div>
        
    </div>
    <div class="manager-area__counters-history  mb-5">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th scope="col">Наименование</th>
                    <th scope="col">Ед.изм</th>
                    <th scope="col">Тариф</th>
                    <th scope="col">Коэфициент</th>
                    <th scope="col">Константа</th>
                    <th scope="col">Редактировать</th>
                    <th scope="col">удалиь</th>
                </tr>
            </thead>

            {% for item in services %}
                <!-- TODO отображать активные но внизу и серые -->
                {% if item.is_active %}
                    <tbody>
                        <tr>
                            <td>{{ item.id }}</td>
                            <td>{{ item.name }}</td>
                            <td>{{ item.unit }}</td>
                            <td class="text-left">{{ item.rate }}</td>
                            <td>{{ item.factor }}</td>
                            <td class="text-700">{% if item.const %} Да {% else %} Нет {% endif %}</td>
                            <td><a href="{% url 'directory:services_update' item.pk %}" type="button" class="btn btn-outline-warning btn-sm" role="button">Редактировать</a></td>
                            <td><a href="{% url 'directory:services_delete' item.pk %}" class="text-danger text-decoration-none">удалить</a></td>
                        </tr>
                    </tbody>
                {% endif %}
            {% endfor %}

        </table> 
    </div>
{% endblock %}

templates/directory/streets.html
{% extends 'directory/base.html' %}
{% load staticfiles %}

{% load crispy_forms_tags %}

{% block menu %}
    {% include 'directory/includes/inc_menu.html' %}
{% endblock menu %}

{% block content %}
    <div class="row  mt-5  mb-3  d-flex justify-content-between">
        <h4 class="col">Улицы города <span class="text-700">{{ city.city }}</span></h4>
        <div class="form-group">
            <a href="{% url 'directory:street_create' city.pk %}" class="btn btn-outline-primary btn-sm" role="button">Добавить улицу</a>
            <a class="btn  btn-outline-secondary btn-sm" role="button" onclick="javascript:history.back(); return false;">Назад</a>
        </div>
        
    </div>
    <div class="manager-area__counters-history  mb-5">
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">ID</th>
                    <th class="text-left" scope="col">Наименование</th>
                    <th scope="col">Дома</th>
                    <th scope="col">Редактировать</th>
                    <th scope="col">удалиь</th>
                </tr>
            </thead>

            {% for street in page_obj %}
            <tbody>
                <tr>
                    <td>{{ street.id }}</td>
                    <td class="text-left">ул.{{ street.street }}</td>
                    <td><a href="{% url 'directory:house' street.pk %}" type="button" class="btn btn-outline-primary btn-sm" role="button">Дома</td>
                    <td><a href="{% url 'directory:street_update' street.pk %}" type="button" class="btn btn-outline-warning btn-sm" role="button">Редактировать</a></td>
                    <td><a href="{% url 'directory:street_delete' street.pk %}" class="text-danger text-decoration-none">удалить</a></td>
                </tr>
            </tbody>
            {% endfor %}
            <div class="pagination  mb-3">
                <span class="step-links">
                    {% if page_obj.has_previous %}
                        <a href="?page={{ page_obj.previous_page_number }}">&laquo; назад    </a>
                    {% endif %}
                    <span class="current  px-3">
                        Страница {{ page_obj.number }} из {{ page_obj.paginator.num_pages }}.
                    </span>
                    {% if page_obj.has_next %}
                        <a href="?page={{ page_obj.next_page_number }}">    вперед &raquo;</a>
                    {% endif %}
                </span>
            </div>
        </table> 
    </div>
{% endblock %}