apps/authnapp/urls.py
from django.contrib.auth.views import (PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import re_path
from django.urls.base import reverse_lazy

import apps.authnapp.views as authnapp
from apps.authnapp.apps import AuthnappConfig
from apps.authnapp.views import ProfileUpdateView

from apps.authnapp.forms import MyPassResetForm, MyPassSetForm, MyPasswordChangeForm

app_name = AuthnappConfig.name

urlpatterns = [
    re_path(r"^login/$", authnapp.login, name="login"),
    re_path(r"^logout/$", authnapp.logout, name="logout"),
    re_path(r"^register/$", authnapp.register, name="register"),
    re_path(r"^edit/(?P<pk>\d+)/$", ProfileUpdateView.as_view(), name="edit"),
    re_path(r"^verify/(?P<email>.+)/(?P<activation_key>\w+)/$", authnapp.verify, name="verify"),
    # change password urls
    re_path(
        r"^password-change/$",
        PasswordChangeView.as_view(
            template_name="authnapp/password_change.html",
            success_url=reverse_lazy("auth:password_change_done"),
            form_class=MyPasswordChangeForm,
        ),
        name="password_change",
    ),
    re_path(
        r"^password-change/done/$",
        PasswordChangeDoneView.as_view(
            template_name="authnapp/password_change_done.html",
        ),
        name="password_change_done",
    ),
    # reset password urls
    re_path(
        r"^password-reset/$",
        PasswordResetView.as_view(
            template_name="authnapp/password_reset.html",
            email_template_name="authnapp/password_reset_email.html",
            success_url=reverse_lazy("auth:password_reset_done"),
            form_class=MyPassResetForm,
        ),
        name="password_reset",
    ),
    re_path(
        r"^password-reset/done/$",
        PasswordResetDoneView.as_view(
            template_name="authnapp/password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    re_path(
        r"^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$",
        PasswordResetConfirmView.as_view(
            template_name="authnapp/password_reset_confirm.html",
            success_url=reverse_lazy("auth:password_reset_complete"),
            form_class=MyPassSetForm,
        ),
        name="password_reset_confirm",
    ),
    re_path(
        r"^password-reset/complete/$",
        PasswordResetCompleteView.as_view(
            template_name="authnapp/password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),
]

newcity/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

import apps.mainapp.views as mainapp

urlpatterns = [
    path("", mainapp.IndexList.as_view(), name="main"),
    path("contact/", mainapp.ContactList.as_view(), name="contact"),
    path("news/", mainapp.NewstList.as_view(), name="news"),
    path("auth/", include("apps.authnapp.urls", namespace="auth")),
    path("directory/", include("apps.directory.urls", namespace="directory")),
    path("person/", include("apps.personalacc.urls", namespace="person")),
    path("invoice/", include("apps.invoice.urls", namespace="invoice")),
    path("admin/", admin.site.urls, name="admin"),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/authnapp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from datetime import timedelta

from django.contrib.auth.base_user import AbstractBaseUser
from django.contrib.auth.models import Group, PermissionsMixin
from django.core.mail import send_mail
from django.core.validators import (MaxLengthValidator, MinLengthValidator,
                                    RegexValidator)
from django.db import models
from django.db.models.signals import post_save
from django.dispatch import receiver
from django.utils.timezone import now
from django.utils.translation import ugettext_lazy as _

from apps.authnapp.managers import UserManager


class User(AbstractBaseUser, PermissionsMixin):
    is_client = models.BooleanField(
        default=True, verbose_name="Пользователь", help_text="Если это житель поставьте галку."
    )
    is_staff = models.BooleanField(
        default=False, verbose_name="Менеджер", help_text="Обозначает, что этот пользователь - Администратор"
    )
    personal_account = models.CharField(
        max_length=128,
        verbose_name="Лицевой счет",
        unique=True,
        help_text="Введите номер лицевого счета: 777777",
        validators=[
            RegexValidator(r"^\d", "Лицевой счет состоит только из цифр!"),
            MinLengthValidator(6, "Лицевой счет состоит из 6 цифр. Вы ввели меньше."),
            MaxLengthValidator(6, "Лицевой счет состоит из 6 цифр. Вы ввели больше."),
        ],
    )
    password = models.CharField(verbose_name="Пароль", max_length=128)
    name = models.CharField(
        verbose_name="ФИО",
        max_length=128,
        null=True,
        blank=True,
        help_text="Иванов Иван Иванович",
        validators=[
            RegexValidator(r"^[a-zA-Zа-яА-ЯёЁ ]*$", "Cпециальные символы и цифры не допускаются!"),
            MinLengthValidator(2),
            MaxLengthValidator(128),
        ],
    )
    email = models.EmailField(
        verbose_name="Email", unique=True, null=True, blank=True, help_text="E-mail в формате - user@example.com"
    )
    phone = models.CharField(
        verbose_name="Телефон",
        max_length=11,
        null=True,
        blank=True,
        help_text="Номер телефона в формате - 79823212334",
        validators=[
            RegexValidator(r"\d{11}", "Телефон должен состоять только из цифр!"),
            MinLengthValidator(11, "Телефон состоит из 11 цифр. Вы ввели меньше."),
            MaxLengthValidator(11, "Телефон состоит из 11 цифр. Вы ввели больше."),
        ],
    )
    is_active = models.BooleanField(verbose_name="Активный", default=True)
    is_superuser = models.BooleanField(
        default=False,
        verbose_name="Суперпользователь",
        help_text="Обозначает, что у этого пользователя есть все разрешения, без их явного назначения.",
    )
    last_login = models.DateTimeField(blank=True, null=True, verbose_name="Последний вход")
    activation_key = models.CharField(verbose_name="Ключ подтверждения", max_length=128, blank=True)
    activation_key_expires = models.DateTimeField(
        verbose_name="Актуальность ключа", default=(now() + timedelta(hours=48))
    )
    objects = UserManager()

    USERNAME_FIELD = "personal_account"
    REQUIRED_FIELDS = ["password", "email"]

    class Meta:
        verbose_name = _("Пользователь")
        verbose_name_plural = _("Пользователи")

    def __str__(self):
        return f"({self.personal_account}) - {self.name}"

    def get_full_name(self):
        full_name = f"{self.name}"
        return full_name.strip()

    def get_short_name(self):
        return self.name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this User"""
        send_mail(subject, message, from_email, [self.email], **kwargs)

    def is_activation_key_expired(self):
        """Checks if the key is up-to-date."""
        if now() <= self.activation_key_expires:
            return False
        else:
            return True
    
    @staticmethod
    def get_by_user_acc(pers_acc):
        return User.objects.filter(personal_account=int(pers_acc)).first()


# Подсели на сигнал после сохранения модели
@receiver(post_save, sender=User)
def add_admin_permission(sender, instance, created, **kwargs):
    if created and not instance.is_superuser:
        if instance.is_client:
            # Если клиент добавляем в группу "Client"
            grupo = Group.objects.get(name="Client")
            grupo.user_set.add(instance)
        if instance.is_staff:
            # Если Менеджер очищаем от всех групп и добавляем в группу "Manager"
            instance.groups.clear()
            grupo = Group.objects.get(name="Manager")
            grupo.user_set.add(instance)

apps/authnapp/forms.py
import hashlib
import random

from django import forms
from django.contrib.auth.forms import (AuthenticationForm, PasswordChangeForm,
                                       PasswordResetForm, SetPasswordForm,
                                       UserChangeForm, UserCreationForm)
from django.contrib.auth.models import Group
from django.forms.models import inlineformset_factory

from apps.directory.models import Appartament, UserProfile

from apps.authnapp.models import User


class BootstrapStylesMixins:
    field_name = None

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        if self.field_name:
            for fieldname in self.field_name:
                self.fields[fieldname].widget.attrs = {"class": "form-control"}
                if fieldname == "is_active" or fieldname == "const":
                    self.fields[fieldname].widget.attrs = {"class": "form_is-active"}
        else:
            raise ValueError("The field_name should be set")


class UserLoginForm(BootstrapStylesMixins, AuthenticationForm):
    # В данном конкретном случае username = personal_account
    field_name = ["username", "password"]


class MyPasswordChangeForm(BootstrapStylesMixins, PasswordChangeForm):
    field_name = ["old_password", "new_password1", "new_password2"]


class MyPassResetForm(BootstrapStylesMixins, PasswordResetForm):
    field_name = ["email"]


class MyPassSetForm(BootstrapStylesMixins, SetPasswordForm):
    field_name = ["new_password1", "new_password2"]


class UserEditForm(BootstrapStylesMixins, UserChangeForm):
    field_name = ["name", "personal_account", "email", "phone"]

    class Meta:
        model = User
        fields = ("name", "personal_account", "email", "phone")
        exclude = ("password",)


class AppartamentEditForm(BootstrapStylesMixins, forms.ModelForm):
    field_name = ["house", "number"]

    class Meta:
        model = Appartament
        fields = ("house", "number")


class UserProfileEditForm(BootstrapStylesMixins, forms.ModelForm):
    field_name = ["gender"]

    class Meta:
        model = UserProfile
        fields = ("gender",)


ProfileFormset = inlineformset_factory(
    User,
    UserProfile,
    form=UserProfileEditForm,
    extra=1,
    can_delete=False,
)


class UserRegisterForm(UserCreationForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs["class"] = "form-control"
            field.help_text = ""

    def save(self):
        user = super(UserRegisterForm, self).save()

        user.is_active = False
        user.groups.add(Group.objects.get(name="Client"))
        salt = hashlib.sha1(str(random.random()).encode("utf8")).hexdigest()[:6]
        user.activation_key = hashlib.sha1((user.email + salt).encode("utf8")).hexdigest()
        user.save()

        return user

    class Meta:
        model = User
        fields = ("personal_account", "name", "password1", "password2", "email")


class AppartamentForm(BootstrapStylesMixins, forms.ModelForm):
    field_name = ["house", "number", "add_number"]

    class Meta:
        model = Appartament
        fields = ("house", "number", "add_number")


AppartamentFormset = inlineformset_factory(
    User,
    Appartament,
    form=AppartamentForm,
    extra=1,
    can_delete=False,
)

apps/authnapp/views.py
from django.conf import settings
from django.contrib import auth
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.mail import send_mail
from django.db import transaction
from django.shortcuts import HttpResponseRedirect, render
from django.urls import reverse, reverse_lazy
from django.views.generic import UpdateView

from apps.authnapp.forms import (ProfileFormset, UserEditForm, UserLoginForm,
                            UserRegisterForm)
from apps.authnapp.models import User


def login(request):
    title = 'Вход | УК "Новый город"'

    login_form = UserLoginForm(data=request.POST or None)
    if request.method == "POST" and login_form.is_valid():
        personal_account = request.POST["username"]
        password = request.POST["password"]

        user = auth.authenticate(personal_account=personal_account, password=password)
        if user and user.is_active:
            auth.login(request, user)
            return HttpResponseRedirect(reverse("main"))

    content = {"title": title, "form": login_form}
    return render(request, "authnapp/login.html", content)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse("main"))


def register(request):
    title = 'Регистрация | УК "Новый город"'

    if request.method == "POST":
        register_form = UserRegisterForm(request.POST, request.FILES)

        if register_form.is_valid():
            user = register_form.save()
            if send_verify_mail(user):
                print("сообщение для подтверждения регистрации отправлено")
                return HttpResponseRedirect(reverse("auth:login"))
            print("ошибка отправки сообщения для подтверждения регистрации")
            return HttpResponseRedirect(reverse("auth:login"))
    else:
        register_form = UserRegisterForm()

    content = {"title": title, "register_form": register_form}
    return render(request, "authnapp/register.html", content)


def send_verify_mail(user):
    verify_link = reverse("auth:verify", args=[user.email, user.activation_key])

    title = f"Подтверждение учетной записи {user.personal_account}"
    message = f"Для подтверждения учетной записи {user.personal_account} \
    на портале {settings.DOMAIN_NAME} перейдите по ссылке: \
    \n{settings.DOMAIN_NAME}{verify_link}"

    print(f"from: {settings.EMAIL_HOST_USER}, to: {user.email}")
    return send_mail(
        title,
        message,
        settings.EMAIL_HOST_USER,
        [user.email],
        fail_silently=False,
    )


def verify(request, email, activation_key):
    try:
        user = User.objects.get(email=email)
        if user.activation_key == activation_key and not user.is_activation_key_expired():
            print(f"user {user} is activated")
            user.is_active = True
            user.save()
            auth.login(request, user, backend="django.contrib.auth.backends.ModelBackend")

            return render(request, "authnapp/verification.html")
        print(f"error activation user: {user}")
        return render(request, "authnapp/verification.html")

    except Exception as e:
        print(f"error activation user : {e.args}")

    return HttpResponseRedirect(reverse("main"))


class ProfileUpdateView(LoginRequiredMixin, UpdateView):
    model = User
    template_name = "authnapp/edit.html"
    success_url = reverse_lazy("main")
    form_class = UserEditForm

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        if self.request.POST:
            context["profile_form"] = ProfileFormset(self.request.POST, instance=self.object)
        else:
            context["profile_form"] = ProfileFormset(instance=self.object)
        return context

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        formset = ProfileFormset(self.request.POST, instance=self.object)

        if not self.request.user.is_staff:
            if form.is_valid() and formset.is_valid():
                return self.form_valid(form, formset)
            return self.form_invalid(form, formset)
        else:
            if form.is_valid():
                return self.form_valid(form, formset)

    def form_valid(self, form, formset):
        if self.request.user.is_staff:
            self.object = form.save()
        else:
            with transaction.atomic():
                self.object = form.save()
                formset.instance = self.object
                formset.save()

        return HttpResponseRedirect(self.get_success_url())

    def form_invalid(self, form, formset):
        return self.render_to_response(
            self.get_context_data(
                form=form,
                appartament_form=formset,
            )
        )

templates/authnapp/base.html
{% load staticfiles %}
{% load solo_tags %}

<!doctype html>
<html lang="ru">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Useful meta tags -->
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="index, follow, noodp">
    <meta name="googlebot" content="index, follow">
    <meta name="google" content="notranslate">
    <meta name="format-detection" content="telephone=no">
    <meta name="keywords" content="">
    <meta name="description" content="">

    {% block css %}

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">

    <!-- Main CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    {% endblock css %}


    <!-- Главная | УК "Новый Город" -->
    <title>
        {% block title %}
        {{ title|capfirst }}
        {% endblock title %}
    </title>
</head>

<body>
    {% get_solo 'personalacc.SiteConfiguration' as site_config %}
    <header class="header">
        <nav class="navbar navbar-expand-lg navbar-light bg-warning">
            <div class="container"> 
                <img class="mr-3" src="{% static 'img/icon/house-fill.svg' %}" alt="House" width="30" height="30">
                <a class="navbar-brand" href="/">{{ site_config.name }}</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                    data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation"> <span class="navbar-toggler-icon"></span>
                </button>

                {% block menu %}
                {% endblock menu %}

            </div>
        </nav>
    </header>

    {% block content %}
    {% endblock content %}

    <!-- JavaScript -->
    <script src="{% static 'js/jquery/jquery-3.6.0.js' %}"></script>
    <script src="{% static 'js/bootstrap/bootstrap.bundle.min.js' %}"></script>
    <!-- jQuery formset section -->
    <!-- <script src="{% static 'js/jquery/jquery.formset.js' %}"></script> -->
    <!-- <script src="{% static 'js/user_profiles.js' %}"></script> -->
    <!-- <script src="{% static 'js/html2canvas.js' %}"></script> -->
    <!-- <script src="{% static 'js/invoice.js' %}"></script> -->
    {% block js %}
    {% endblock %}
</body>

</html>

templates/authnapp/edit.html
{% extends 'base.html' %}
{% load staticfiles %}

{% load auth_extras %}
{% load crispy_forms_tags %}

{% block menu %}
    {% include 'mainapp/includes/inc_menu.html' %}
{% endblock menu %}

{% block content %}

<section class="edit  my-5">
    <div class="container  d-flex  justify-content-center">
        <div class="edit__item">

            <form class="form-horizontal" action="{% url 'auth:edit' object.pk %}" method="post"
                enctype="multipart/form-data">
                <h1 class="mb-3">Редактирование профиля</h1>
                {% csrf_token %}
                {% if next_page %}
                    <input type="hidden" name="next_page" value="{{ next_page }}">
                {% endif %}

                
                {% comment %}
                    {% for field in form %}
                        <div class="form-group">
                            {{ field.label }}
                            {{ field }}
                        </div>

                        {% if field.errors %}
                            <div class="alert  alert-danger">
                                {{ field.errors }}
                            </div>
                        {% endif %}
                    {% endfor %}


                    {% if not user.is_staff and not user.is_superuser %}
                    <table class="table">
                        {{ profile_form.management_form }}
                        {{ profile_form.non_form_errors }}
                        
                            {% for form in profile_form %}
                            <div class="list-inline">
                                {{ form.as_p }}
                            </div>
                                {% if form.errors %}
                                    <div class="alert  alert-danger">
                                        {{ form.errors }}
                                    </div>
                                {% endif %}
                            {% endfor %}
                    </table>
                    {% endif %}
                {% endcomment %}

                {% for field in form %}
                    <div class="row mb-2">
                        {% if field.label != "" and field.label != "Пароль" %}
                            <label class="col-sm-4 col-form-label" for="{{ field.auto_id }}">{{ field.label }}</label>
                            <div class="col-sm-8">
                                {{ field }}
                            </div>
                        {% else %}
                        {% endif %}
                    </div>
                {% endfor %}
                    
                {% if not user.is_staff and not user.is_superuser %}
                    {{ profile_form.management_form }}
                    {{ profile_form.non_form_errors }}
                    {% for field in profile_form %}
                        <div class="row mb-2">
                            {% if field.label != "" and field.label != "Пароль"%}
                                <label class="col-sm-4 col-form-label" for="{{ field.auto_id }}">{{ field.label }}</label>
                                <div class="col-sm-8">
                                    {{ field }}
                                </div>
                            {% endif %}
                        </div>
                    {% endfor %}
                {% endif %}
                <br>

                <div class="change_pass  pb-5">
                    <a href="{% url 'authnapp:password_change' %}"
                        class="col  text-right  text-decoration-none">Изменить пароль</a>
                </div>

                <input class="btn btn-outline-primary btn-block  mb-3" type="submit" value="сохранить">

            </form>
            <a href="{% url 'main' %}" class="btn btn-outline-secondary btn-block" role="button">
                на главную
            </a>

        </div>
    </div>
</section>
{% endblock %}

{% block js %}
<script>
    $('#id_password').parent().hide();
    $('#id_personal_account').hide();
    $('#id_personal_account').before('<p style="font-weight: bold;">{{ user.personal_account }}</p>');
</script>
{% endblock %}

templates/authnapp/login.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block menu %}
    {% include 'mainapp/includes/inc_menu.html' %}
{% endblock menu %}

{% block content %}
<section class="login  pt-5">
    <div class="container  d-flex  flex-column  justify-content-center  align-items-center">
        <h1>Авторизация</h1>
        <div class="login__item  pt-5">
            <form class="form-horizontal" action="{% url 'auth:login' %}" method="post">
                {% csrf_token %}
                {% if next_page %}
                    <input type="hidden" name="next_page" value="{{ next_page }}">
                {% endif %}
                {% if form.errors %}
                    <div class="alert  alert-danger">
                        {{ form.non_field_errors }}
                    </div>
                {% endif %}
                {% for field in form %}
                    <div class="form-floating mb-4">
                        {{ field.label }}
                        {{ field }}
                    </div>
                    {% if field.errors %}
                        <div class="alert  alert-danger">
                            {{ field.errors }}
                        </div>
                    {% endif %}
                {% endfor %}
                <br>
                <a href='{% url "auth:password_reset" %}' class="text-decoration-none  text-right">Забыли пароль?</a>
                <button class="w-100 btn btn-lg btn-primary" type="submit">Войти</button>
            </form>
        </div>
    </div>
</section>
{% endblock content %}

templates/authnapp/password_change.html
{% extends "base.html" %}

{% block title %}Изменение пароля{% endblock %}

{% block menu %}
    {% include 'mainapp/includes/inc_menu.html' %}
{% endblock menu %}

{% block content %}

<section class="password  mt-5">
    <div class="container  d-flex  justify-content-center">
        <div class="password__items">

            <h1 class="text-center  mb-5">Изменить пароль</h1>
            <form action="{% url 'auth:password_change' %}" method="post">
                {% csrf_token %}
                {% for error in form.non_field_errors %}
                    <div class="alert  alert-danger">
                        {{ error }}
                    </div>
                {% endfor %}

                {% for field in form %}
                    <div class="form-group">
                        {{ field.label }}
                        {{ field }}
                    </div>

                    {% if field.errors %}
                        <div class="alert  alert-danger">
                            {{ field.errors }}
                        </div>
                    {% endif %}
                {% endfor %}
                <button type="submit" class="btn btn-success">Изменить</button>

            </form>
        </div>
    </div>
</section>
{% endblock %}

templates/authnapp/password_change_done.html
{% extends "base.html" %}

{% block title %}Изменение пароля{% endblock %}

{% block menu %}
    {% include 'mainapp/includes/inc_menu.html' %}
{% endblock menu %}

{% block content %}

<section class="password  mt-5">
    <div class="container  d-flex  justify-content-center">
        <div class="password__items">
            <div class="mt-5  flex-column  d-flex  justify-content-center">
                <h1>Пароль изменен!</h1>
                <div class="alert  alert-success  mt-3  mb-5">
                    <p>Ваш пароль был успешно изменен.</p>
                </div>
                <a href="{% url 'main' %}" class="text-decoration-none  text-center">На главную</a>
            </div>
        </div>
    </div>
</section>
{% endblock %}

templates/authnapp/password_reset.html
{% extends "base.html" %}

{% block title %}Сброс пароля{% endblock %}

{% block menu %}
    {% include 'mainapp/includes/inc_menu.html' %}
{% endblock menu %}

{% block content %}
    <section class="password  pt-5">
        <div class="container  d-flex  justify-content-center">
            <div class="password__items">
                <h1 class="text-center  mb-5">Сброс пароля</h1>
                <div class="alert  alert-warning  mb-5">Пожалуйста, введите Ваш Email</div>
                <form method="post">
                    {% csrf_token %}
                    {% for field in form %}
                        <div class="form-floating  mb-4">
                            {{ field.label }}
                            {{ field }}
                        </div>
                    {% endfor %}
                    <button class="w-100 btn btn-lg btn-primary" type="submit">Сброс</button>
                </form>
            </div>
        </div>
    </section>
{% endblock %}

templates/authnapp/password_reset_complete.html
{% extends "base.html" %}

{% block title %}Reset your password{% endblock %}

{% block menu %}
    {% include 'mainapp/includes/inc_menu.html' %}
{% endblock menu %}

{% block content %}
    <section class="password  mt-5">
        <div class="container  d-flex  justify-content-center">
            <div class="password__items">
                <h1 class="mt-5 text-center">Пароль сброшен!</h1>
            </div>
        </div>
    </section>
{% endblock %}

templates/authnapp/password_reset_confirm.html
{% extends "base.html" %}

{% block title %}Reset your password{% endblock %}

{% block menu %}
    {% include 'mainapp/includes/inc_menu.html' %}
{% endblock menu %}

{% block content %}
<section class="password  mt-5">
    <div class="container  d-flex  justify-content-center">
        <div class="password__items">
            <h1 class="mb-5">Введите новый пароль:</h1>
            <form enctype="multipart/form-data" method="post">
                {% csrf_token %}
                {% for field in form %}
                    <div class="form-group">
                        {{ field.label }}
                        {{ field }}
                    </div>
                    {% if field.errors %}
                        <div class="alert  alert-danger">
                            {{ field.errors }}
                        </div>
                    {% endif %}
                {% endfor %}
                <button type="submit" class="btn btn-success">Сбросить</button>
            </form>
        </div>
    </div>
</section>
{% endblock %}

templates/authnapp/password_reset_done.html
{% extends "base.html" %}

{% block title %}Reset your password{% endblock %}

{% block menu %}
    {% include 'mainapp/includes/inc_menu.html' %}
{% endblock menu %}

{% block content %}
    <section class="password  pt-5">
        <div class="container">
            <div class="password__items  d-flex  flex-column  align-items-center">
                <h1 class="text-center">Мы отправили вам E-mail</h1>
                <div class="alert  alert-info  mt-5"  style="max-width: 600px;">Пожалуйста, проверьте почтовый ящик, для получения подробных инструкций.</div>
            </div>
        </div>
    </section>
{% endblock %}

templates/authnapp/password_reset_email.html
Someone asked for password reset for email {{ email }}. Follow thelink below:
{{ protocol }}://{{ domain }}{% url "auth:password_reset_confirm" uidb64=uid token=token %}
Your username, in case you've forgotten: {{ user.get_username }}

templates/authnapp/register.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block menu %}
    {% include 'authnapp/includes/inc_menu.html' %}
{% endblock menu %}

{% block content %}
    <div class="d-flex  justify-content-center  my-5">
        <form class="form-horizontal  w-100  main-form" action="{% url 'auth:register' %}" method="post" enctype="multipart/form-data">
            {% csrf_token %}
            {{ register_form.as_p }}
            <br>
            <input class="form-control" type="submit" value="зарегистрироваться">
        </form>
    </div>
{% endblock %}

templates/authnapp/verify.html
{% extends 'base.html' %}
{% load staticfiles %}


{% block content %}
{% if user %}
    <h3>Поздравляем!</h3>
    <br>
    <h4>Пользователь {{user.personal_account}} подтвержден.</h4>
    {% else %}
    <h3>Верификация не пройдена.</h3>
    {% endif %}
    <br>
    <a href="{% url 'main' %}" class="btn  form-control" role="button"> на главную</a>
{% endblock %}