apps/authnapp/urls.py
from django.contrib.auth.views import (PasswordChangeDoneView,
                                       PasswordChangeView,
                                       PasswordResetCompleteView,
                                       PasswordResetConfirmView,
                                       PasswordResetDoneView,
                                       PasswordResetView)
from django.urls import re_path
from django.urls.base import reverse_lazy

import apps.authnapp.views as authnapp
from apps.authnapp.apps import AuthnappConfig
from apps.authnapp.views import ProfileUpdateView

from apps.authnapp.forms import MyPassResetForm, MyPassSetForm, MyPasswordChangeForm

app_name = AuthnappConfig.name

urlpatterns = [
    re_path(r"^login/$", authnapp.login, name="login"),
    re_path(r"^logout/$", authnapp.logout, name="logout"),
    re_path(r"^register/$", authnapp.register, name="register"),
    re_path(r"^edit/(?P<pk>\d+)/$", ProfileUpdateView.as_view(), name="edit"),
    re_path(r"^verify/(?P<email>.+)/(?P<activation_key>\w+)/$", authnapp.verify, name="verify"),
    # change password urls
    re_path(
        r"^password-change/$",
        PasswordChangeView.as_view(
            template_name="authnapp/password_change.html",
            success_url=reverse_lazy("auth:password_change_done"),
            form_class=MyPasswordChangeForm,
        ),
        name="password_change",
    ),
    re_path(
        r"^password-change/done/$",
        PasswordChangeDoneView.as_view(
            template_name="authnapp/password_change_done.html",
        ),
        name="password_change_done",
    ),
    # reset password urls
    re_path(
        r"^password-reset/$",
        PasswordResetView.as_view(
            template_name="authnapp/password_reset.html",
            email_template_name="authnapp/password_reset_email.html",
            success_url=reverse_lazy("auth:password_reset_done"),
            form_class=MyPassResetForm,
        ),
        name="password_reset",
    ),
    re_path(
        r"^password-reset/done/$",
        PasswordResetDoneView.as_view(
            template_name="authnapp/password_reset_done.html",
        ),
        name="password_reset_done",
    ),
    re_path(
        r"^password-reset/confirm/(?P<uidb64>[-\w]+)/(?P<token>[-\w]+)/$",
        PasswordResetConfirmView.as_view(
            template_name="authnapp/password_reset_confirm.html",
            success_url=reverse_lazy("auth:password_reset_complete"),
            form_class=MyPassSetForm,
        ),
        name="password_reset_confirm",
    ),
    re_path(
        r"^password-reset/complete/$",
        PasswordResetCompleteView.as_view(
            template_name="authnapp/password_reset_complete.html",
        ),
        name="password_reset_complete",
    ),
]

apps/personalacc/urls.py
from django.urls import re_path

import apps.personalacc.views as personalacc
from apps.personalacc.apps import PersonalaccConfig

app_name = PersonalaccConfig.name

urlpatterns = [
    re_path(r"^user/$", personalacc.UserPageCreate.as_view(), name="user"),
    re_path(r"^manager/$", personalacc.ManagerPageCreate.as_view(), name="manager"),
    # Autocomplete
    re_path(r"^manager/autocomplete/$", personalacc.UserAutocomplete.as_view(), name="autocomplete"),
    
    re_path(r"^manager/formation_payments/$", personalacc.FormationPayments.as_view(), name="formation_payments"),
    re_path(r"^manager/receivable/$", personalacc.AccountsReceivableListView.as_view(), name="receivable"),
    
    re_path(r"^manager/house_history/$", personalacc.HouseHistoryListView.as_view(), name="house_history"),
    re_path(r"^manager/recalc_history/$", personalacc.RecalcHistoryListView.as_view(), name="recalc_history"),
    re_path(
        r"^manager/privileges_history/$", personalacc.PrivilegesHistoryListView.as_view(), name="privileges_history"
    ),
    re_path(r"^manager/subsidies_history/$", personalacc.SubsidiesHistoryListView.as_view(), name="subsidies_history"),
    re_path(r"^manager/payments_history/$", personalacc.PaymentsHistoryListView.as_view(), name="payments_history"),
]

newcity/urls.py
from django.conf import settings
from django.conf.urls import include
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path

import apps.mainapp.views as mainapp

urlpatterns = [
    path("", mainapp.IndexList.as_view(), name="main"),
    path("contact/", mainapp.ContactList.as_view(), name="contact"),
    path("news/", mainapp.NewstList.as_view(), name="news"),
    path("auth/", include("apps.authnapp.urls", namespace="auth")),
    path("directory/", include("apps.directory.urls", namespace="directory")),
    path("person/", include("apps.personalacc.urls", namespace="person")),
    path("invoice/", include("apps.invoice.urls", namespace="invoice")),
    path("admin/", admin.site.urls, name="admin"),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/mainapp/models.py
import logging
import datetime
from decimal import Decimal

from django.contrib.postgres.fields import JSONField
from django.db import models
from django.db.models.deletion import CASCADE, SET_NULL
from django.db.models.signals import post_save, pre_delete
from django.dispatch import receiver

from apps.authnapp.models import User
from apps.directory.models import House, Services
from apps.mainapp.mixins.utils import (PERIOD, ActiveMixin, CreateUpdateMixin,
                                  WaterCounterMixin)

from newcity.config_logger import logger


# Общедомовой счетчик (ТЕКУЩИЕ показания)
class HouseCurrent(WaterCounterMixin):
    period = models.DateField(verbose_name="Период", default=datetime.datetime.now().replace(day=1))
    house = models.ForeignKey(House, verbose_name="Дом", null=True, on_delete=SET_NULL)

    class Meta:
        ordering = ("-updated",)
        verbose_name = "Домовой счетчик (текущий)"
        verbose_name_plural = "Домовые счетчики (текущие)"

    def __str__(self):
        return f"Период - {self.period}, ул.{self.house.street.street}, Дом №{self.house.number}, к.{self.house.add_number}"

    @staticmethod
    def get_item(user):
        return HouseCurrent.objects.filter(user=user)

    @staticmethod
    def get_qty_last_items(qty):
        return HouseCurrent.objects.all()[:qty]


# Общедомовой счетчик (ИСТОРИЯ показания)
class HouseHistory(WaterCounterMixin):
    period = models.DateField(verbose_name="Период", default=datetime.datetime.now().replace(day=1))
    house = models.ForeignKey(House, verbose_name="Дом", null=True, on_delete=SET_NULL)

    class Meta:
        ordering = ("-updated",)
        verbose_name = "Домовой счетчик (история)"
        verbose_name_plural = "01 Домовые счетчики (история)"

    def __str__(self):
        return f"Период - {self.period}, ул.{self.house.street.street}, Дом №{self.house.number}, к.{self.house.add_number}"

    @staticmethod
    # Вместо User - Appartaments?
    def get_item(user):
        return HouseHistory.objects.filter(user=user)

    @staticmethod
    def get_last_val(house):
        return HouseHistory.objects.filter(house=house)[0:1]

    @staticmethod
    def get_qty_last_items(qty):
        return HouseCurrent.objects.all()[:qty]

    # При удалении ловим и сохраняем объект ДОМОВЫЕ ПОКАЗАНИЯ
    @receiver(pre_delete, sender=HouseCurrent)
    def copy_arhive_current_to_history_house(sender, instance, **kwargs):
        house = instance.house_id
        period = instance.period
        upd_val = {
            "col_water": instance.col_water,
            "hot_water": instance.hot_water,
        }
        obj, created = HouseHistory.objects.update_or_create(house_id=house, period=period, defaults=upd_val)


# Среднедомовой показатель
class Standart(ActiveMixin):
    period = models.DateField(verbose_name="Период", default=datetime.datetime.now().replace(day=1))
    house = models.ForeignKey(House, verbose_name="Дом", null=True, on_delete=SET_NULL)
    # Значения хранятся на 1 кв.м
    col_water = models.DecimalField(verbose_name="Норматив ХВС", max_digits=11, decimal_places=6)
    hot_water = models.DecimalField(verbose_name="Норматив ХГС", max_digits=11, decimal_places=6)

    class Meta:
        ordering = ("-period",)
        verbose_name = "Норматив"
        verbose_name_plural = "Нормативы"

    def __str__(self):
        return f"Период {self.period} - ул.{self.house.street.street}, д.{self.house.number}"

    @staticmethod
    def get_last_val(house):
        return Standart.objects.filter(house=house).first()

    # При изменении текущих домовых показаний перещитываем норматив
    @receiver(post_save, sender=HouseCurrent)
    def calculation_of_standart_to_house_current(sender, instance, **kwargs):
        house = instance.house_id
        # period = PERIOD
        # TODO PERIOD
        period = instance.period
        hist = HouseHistory.get_last_val(house)[0]
        sq = House.get_item(house)[0].sq_home
        upd_val = {
            "col_water": (Decimal(instance.col_water) - Decimal(hist.col_water)) / sq,
            "hot_water": (Decimal(instance.hot_water) - Decimal(hist.hot_water)) / sq,
        }
        obj, created = Standart.objects.update_or_create(house_id=house, period=period, defaults=upd_val)


# Текущие показания счетчиков (индивидуальные)
class CurrentCounter(WaterCounterMixin):
    user = models.ForeignKey(User, verbose_name="Пользователь", on_delete=CASCADE)
    period = models.DateField(verbose_name="Период", default=datetime.datetime.now().replace(day=1))

    class Meta:
        ordering = ("-period",)
        verbose_name = "Индивидуальный счетчик (текущий)"
        verbose_name_plural = "Индивидуальные счетчики (текущие)"

    def __str__(self):
        return f"({self.user.personal_account}) - {self.user.name} ({self.period})"

    @staticmethod
    def get_last_val(user):
        period = PERIOD
        try:
            obj = CurrentCounter.objects.filter(user=user).latest("period")
            if obj.period.month == period.month:
                return obj
            else:
                return None
        except Exception as e:
            logger.error(f'Не введены индивидуальные счетчики, err: {e}')
            return None


# История показания счетчиков (индивидуальные)
class HistoryCounter(WaterCounterMixin):
    user = models.ForeignKey(User, verbose_name="Пользователь", null=True, on_delete=SET_NULL)
    period = models.DateField(verbose_name="Период", default=datetime.datetime.now().replace(day=1))

    class Meta:
        ordering = ("-period",)
        verbose_name = "Индивидуальный счетчик (история)"
        verbose_name_plural = "02 Индивидуальные счетчики (история)"

    def __str__(self):
        return f"({self.user.personal_account}) - {self.user.name} ({self.period})"

    @staticmethod
    def get_last_val(user):
        return HistoryCounter.objects.filter(user=user).first()

    # При удалении ловим и сохраняем объект ИНДИВИДУАЛЬНЫЕ ПОКАЗАНИЯ
    @receiver(pre_delete, sender=CurrentCounter)
    def copy_arhive_current_to_history(sender, instance, **kwargs):
        user = instance.user
        period = instance.period
        upd_val = {
            "col_water": instance.col_water,
            "hot_water": instance.hot_water,
        }
        obj, created = HistoryCounter.objects.update_or_create(user=user, period=period, defaults=upd_val)


# Перерасчеты
class Recalculations(ActiveMixin):
    user = models.ForeignKey(User, verbose_name="Пользователь", null=True, on_delete=SET_NULL)
    period = models.DateField(verbose_name="Период", default=datetime.datetime.now().replace(day=1))
    service = models.ForeignKey(Services, verbose_name="Услуга", null=True, on_delete=SET_NULL)
    recalc = models.DecimalField(verbose_name="Сумма", max_digits=10, decimal_places=2, default=0)
    desc = models.TextField(verbose_name="Описание", blank=True, null=True)
    is_auto = models.BooleanField(verbose_name="Автоматический", default=False)

    class Meta:
        ordering = ("-updated",)
        verbose_name = "Перерасчет"
        verbose_name_plural = "Перерасчеты"

    def __str__(self):
        return f"({self.user.personal_accaunt}) - {self.service} ({self.period})"

    @staticmethod
    def get_last_val(user):
        return Recalculations.objects.filter(user=user).first()

    @staticmethod
    def get_items(user, period):
        return Recalculations.objects.filter(user=user, period=period)

    def get_sum_period(self, period):
        recalc = Recalculations.objects.filter(user=self.user, period=period)
        return sum(abs(el.recalc) for el in recalc)

    @staticmethod
    def get_qty_last_items(qty):
        return Recalculations.objects.all()[:qty]


# Постоянные платежи (расчет по формуле = const*rate или = const)
class ConstantPayments(ActiveMixin):
    user = models.ForeignKey(User, verbose_name="Пользователь", on_delete=CASCADE)
    data = JSONField(verbose_name="data")
    total = models.DecimalField(verbose_name="Сумма", max_digits=8, decimal_places=3)
    pre_total = models.DecimalField(verbose_name="Сумма", max_digits=8, decimal_places=3)

    class Meta:
        verbose_name = "Платеж (постоянные)"
        verbose_name_plural = "Платежи (постоянные)"

    def __str__(self):
        return f"({self.user.personal_account}) - {self.user.name}"

    @staticmethod
    def get_item(user):
        return ConstantPayments.objects.filter(user=user)


# Переменные платежи (зависящие от счетчиков)
class VariablePayments(ActiveMixin):
    user = models.ForeignKey(User, verbose_name="Пользователь", on_delete=CASCADE)
    period = models.DateField(verbose_name="Период", default=datetime.datetime.now().replace(day=1))
    data = JSONField(verbose_name="data")
    total = models.DecimalField(verbose_name="Итого", max_digits=10, decimal_places=2, default=0)
    pre_total = models.DecimalField(verbose_name="Итого", max_digits=10, decimal_places=2, default=0)

    class Meta:
        ordering = ("-period",)
        verbose_name = "Платеж (перепенные)"
        verbose_name_plural = "Платежи (переменные)"

    def __str__(self):
        return f"({self.user.personal_account}) - {self.user.name} ({self.period})"

    @staticmethod
    def get_items(user):
        return VariablePayments.objects.filter(user=user)

    @staticmethod
    def get_last_val(user):
        try:
            value = VariablePayments.objects.filter(user=user).first()
            return value
        except Exception as e:
            logger.error(e)
            return None


# Данные для шапки платежки
class HeaderData(CreateUpdateMixin):
    user = models.ForeignKey(User, verbose_name="Пользователь", null=True, on_delete=SET_NULL)
    data = JSONField(verbose_name="Данные")

    class Meta:
        verbose_name = "(Платежка) данные шапки"
        verbose_name_plural = "(Платежка) данные шапок"

    def __str__(self):
        return f"({self.user.personal_account}) - {self.user.name}"

apps/mainapp/views.py
from django.views.generic import ListView

from apps.directory.models import PostNews
from apps.personalacc.models import SiteConfiguration


class IndexList(ListView):
    model = PostNews
    template_name = "mainapp/index.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Главная | ООО Новый город"
        context["news"] = PostNews.get_items()[:4]
        context["config"] = SiteConfiguration.get_solo()
        return context


class ContactList(ListView):
    model = PostNews
    template_name = "mainapp/contact.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Контакты | ООО Новый город"
        context["config"] = SiteConfiguration.get_solo()
        return context


class NewstList(ListView):
    model = PostNews
    paginate_by = 10
    template_name = "mainapp/news.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["title"] = "Новости | ООО Новый город"
        context["news"] = PostNews.get_items()
        context["config"] = SiteConfiguration.get_solo()
        return context

templates/mainapp/includes/footer.html
<footer class="footer">
    <div class="container">
        <div class="footer__item">
            <div class="footer__top">
                <div class="footer__top-item">
                    <p class="footer__city">{{ site_config.name }}</p>
                    <p><a class="footer__link" href="{% url 'news' %}">Новости</a></p>
                    <p><a class="footer__link" href="{% url 'contact' %}">Контакты</a></p>
                    <p><a class="footer__link" href="#">Политика конфеденциальности</a></p>
                </div>
            </div>
            <hr class="footer__line">
            <div class="footer__bottom">
                <p class="footer__copy">{{ site_config.footer_copyright }} {% now "Y" %} г. </p>
                <p class="footer__parent">A &amp;&amp; A</p>
            </div>
        </div><!-- ./footer__item -->
    </div><!-- ./container -->
</footer>

templates/mainapp/includes/head_meta.html
<!-- Required meta tags -->
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- Useful meta tags -->
<meta http-equiv="x-ua-compatible" content="ie=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="robots" content="index, follow, noodp">
<meta name="googlebot" content="index, follow">
<meta name="google" content="notranslate">
<meta name="format-detection" content="telephone=no">
<meta name="keywords" content="">
<meta name="description" content="">

templates/mainapp/includes/inc_menu.html
{% load auth_extras %}

<div class="collapse navbar-collapse  d-flex  justify-content-between" id="navbarSupportedContent">
    <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item"> <a class="nav-link {% if request.resolver_match.url_name == 'main' %}active{% endif %}"
                aria-current="page" href="/">Главная</a> </li>
        <li class="nav-item"> <a class="nav-link {% if request.resolver_match.url_name == 'main' %}active{% endif %}"
                aria-current="page" href="{% url 'news' %}">Новости</a> </li>
        <li class="nav-item"> <a class="nav-link {% if request.resolver_match.url_name == 'main' %}active{% endif %}"
                aria-current="page" href="{% url 'contact' %}">Контакты</a> </li>
    </ul>
    <div class="navbar-nav  dropdown">
        {% if user.is_authenticated %}
            {% if request.user|has_group:"Client" %}
            <a class="nav-link  text-dark  dropdown-toggle" data-toggle="dropdown" id="dropdownMenuButton" aria-haspopup="true"
                aria-expanded="false">Пользователь</a>
                <span class="caret"></span>
            {% elif request.user|has_group:"Manager" %}
            <a class="nav-link  text-dark  dropdown-toggle" data-toggle="dropdown" id="dropdownMenuButton" aria-haspopup="true"
                aria-expanded="false">Менеджер</a>
                <span class="caret"></span>
            {% elif user.is_superuser %}
            <a class="nav-link text-dark" aria-current="page"
                href="{% url 'admin:index' %}">Админка</a>
            {% endif %}
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                <a class="dropdown-item" href="{% url 'auth:edit' user.pk %}">{{ "профиль"|upper }}</a>
                {% if request.user|has_group:"Client" %}
                <a class="dropdown-item" href="{% url 'person:user' %}">{{ "Кабинет"|upper }}</a>
                {% elif request.user|has_group:"Manager" %}
                <a class="dropdown-item" href="{% url 'person:manager' %}">{{ "Кабинет"|upper }}</a>
                {% endif %}
            </div>
        {% endif %}
        <ul>
            <li class="nav-item">
                {% if user.is_authenticated %}
                <a class="nav-link text-dark" aria-current="page" href="{% url 'auth:logout' %}">Выйти</a>
                {% else %}
                <a class="nav-link text-dark" aria-current="page" href="{% url 'auth:login' %}">Войти</a>
                {% endif %}
            </li>
        </ul>
    </div>
</div>



         